### ISSUE TITLE
do not authenticate if the remote server is down

### ISSUE THREAD

**Issue by mcollina** [charlesread/fastify-jwt-webapp#10]
See https://github.com/charlesread/fastify-jwt-webapp/blob/aa5bb255298e440dc7c33100d679d10c3f33ccc2/plugin.js#L53

Inside the `catch()`  that exception has to be handled somehow.

**Comment by charlesread** [comment]
So `authorizationCallback` is a totally optional callback that the user can use to do something after successful authentication, whatever they want, so to my mind the plugin should be completely agnostic to whether or not `authorizationCallback` actually succeeds.  I added some language in the README in f9ff4e4 that addresses this.
