### ISSUE TITLE
do not store configs as a global

### ISSUE THREAD

**Issue by mcollina** [charlesread/fastify-jwt-webapp#4]
https://github.com/charlesread/fastify-jwt-webapp/blob/master/lib/util.js#L21-L27 store some configuration in the module scope. You should do `module.exports = function build (config) { return implementation }` instead (and the other functions are defined in the build function).

**Comment by charlesread** [comment]
fixed in 1b61582

**Comment by trivikr** [comment]
Commit: 1b61582
